version: '3'
services:
    nginx:
        image: nginx
        ports:
          - "80:80"
        volumes:
          - .:/app:cached
          - ./docker/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - php

    php:
        build: ./docker/php
        volumes:
          - .:/app:cached
        working_dir: /app

    db:
        image: mysql:5.7
        ports:
          - 3306:3306
        volumes:
          - ./mysqldata:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=12345
          - MYSQL_USER=root
          - MYSQL_PASSWORD=12345
